

export const embalajes = [
    { value: "N/A", label: "N/A" },
    { value: "2C", label: "2C Barril de Madera" },
    { value: "3H", label: "3H Bidón de Plástico" },
    { value: "5H", label: "5H Bolsa Tejido de Plástico" },
    { value: "BA", label: "BA Barril" },
    { value: "BJ", label: "BJ Balde" },
    { value: "BO", label: "BO Botella Cilindrica no Protegida" },
    { value: "BQ", label: "BQ Botella Cilindrica Protegida" },
    { value: "BS", label: "BS Botella Bulbosa sin protección" },
    { value: "BW", label: "BW Caja para Liquididos" },
    { value: "CI", label: "CI Lata" },
    { value: "DR", label: "DR Tambor" },
    { value: "EC", label: "EC Bolsa Plastica" },
    { value: "HG", label: "HG Pipa" },
    { label: "IH Barril Plástico", value: "IH" },
    { value: "JC", label: "JC Bidón rectangular" },
    { value: "JY", label: "JY Bidón Cilíndrico" },
    { value: "PL", label: "PL Cubeta" },
    { value: "PR", label: "PR Recipiente Plastico" },
    { value: "QF", label: "QF Tonel Plástico tapa no desmontable" },
    { value: "QG", label: "QG Tonel Plástico con tapa desmontable" },
    { value: "QH", label: "QH Barril de madera con tapón" },
    { value: "QJ", label: "QJ Barril madera tapadera desmontable" },
    { value: "QM", label: "QM Bidón plástico tapadera no desmontable" },
    { value: "QN", label: "QN Bidón plástico, tapadera desmontable" },
    { value: "TO", label: "TO Tonel." },
    { value: "TY", label: "TY Tanque Cilindrico" },
    { value: "VA", label: "VA Tanque" },
    { value: "VL", label: "VL Liquido a Granel" },
    { value: "WB", label: "WB Botella Enfundada" }
];

export const paises = [
    { value: "AF", label: "AFGANISTAN" },
    { value: "AL", label: "ALBANIA" },
    { value: "DE", label: "ALEMANIA (UNIFICADA)" },
    { value: "AD", label: "ANDORRA" },
    { value: "AO", label: "ANGOLA" },
    { value: "AI", label: "ANGUILLA" },
    { value: "AQ", label: "ANTARTIDA" },
    { value: "AG", label: "ANTIGUA Y BARBADOS" },
    { value: "DZ", label: "ARGELIA" },
    { value: "AR", label: "ARGENTINA" },
    { value: "AM", label: "ARMENIA" },
    { value: "AW", label: "ARUBA" },
    { value: "AU", label: "AUSTRALIA" },
    { value: "AT", label: "AUSTRIA" },
    { value: "AZ", label: "AZERBALIAN" },
    { value: "BS", label: "BAHAMAS" },
    { value: "BH", label: "BAHREIN" },
    { value: "BD", label: "BANGLADESH" },
    { value: "BB", label: "BARBADOS" },
    { value: "BE", label: "BELGICA" },
    { value: "BZ", label: "BELICE (HONDURAS BRITANICA)" },
    { value: "BJ", label: "BENIN" },
    { value: "BM", label: "BERMUDA" },
    { value: "BY", label: "BIELORRUSIA, RUSIA BLANCA" },
    { value: "BO", label: "BOLIVIA" },
    { value: "BA", label: "BOSNIA Y HERZSEGOVINA" },
    { value: "BW", label: "BOTSWANA" },
    { value: "BV", label: "BOUVET,ISLA" },
    { value: "BR", label: "BRASIL" },
    { value: "BN", label: "BRUNEI DARUSSALAM" },
    { value: "BG", label: "BULGARIA" },
    { value: "BF", label: "BURKINA FASO" },
    { value: "BI", label: "BURUNDI" },
    { value: "BT", label: "BUTAN" },
    { value: "CV", label: "CABO VERDE" },
    { value: "KY", label: "CAIMAN ISLAS" },
    { value: "KH", label: "CAMBOYA" },
    { value: "CM", label: "CAMERUN" },
    { value: "CA", label: "CANADA" },
    { value: "CF", label: "CENTROAFRICANA REPUBLICA" },
    { value: "TD", label: "CHAD" },
    { value: "CZ", label: "CHECA REPUBLICA" },
    { value: "CL", label: "CHILE" },
    { value: "CN", label: "CHINA" },
    { value: "CY", label: "CHIPRE" },
    { value: "CC", label: "COCOS (KEELING) ISLAS" },
    { value: "CO", label: "COLOMBIA" },
    { value: "KM", label: "COMORES" },
    { value: "CG", label: "CONGO, REP. POPULAR DEL" },
    { value: "CD", label: "CONGO, REPUBLICA DEMOCRATICA" },
    { value: "CK", label: "COOK ISLAS" },
    { value: "CI", label: "COSTA DE MARFIL (COTE D'IVOIRE" },
    { value: "CR", label: "COSTA RICA" },
    { value: "HR", label: "CROACIA" },
    { value: "CU", label: "CUBA" },
    { value: "CW", label: "CURAZAO" },
    { value: "DK", label: "DINAMARCA" },
    { value: "DJ", label: "DJIBOUTH" },
    { value: "DM", label: "DOMINICA" },
    { value: "DO", label: "DOMINICANA REPUBLICA" },
    { value: "EC", label: "ECUADOR" },
    { value: "GQ", label: "ECUATORIAL GUINEA" },
    { value: "EG", label: "EGIPTO" },
    { value: "SV", label: "EL SALVADOR" },
    { value: "AE", label: "EMIRATOS ARABES UNIDOS" },
    { value: "ER", label: "ERITREA" },
    { value: "SK", label: "ESLOVAKIA" },
    { value: "SI", label: "ESLOVENIA" },
    { value: "ES", label: "ESPANA" },
    { value: "US", label: "ESTADOS UNIDOS" },
    { value: "EE", label: "ESTONIA" },
    { value: "ET", label: "ETIOPIA" },
    { value: "FK", label: "FALKLAND ISLAS (MALVINAS)" },
    { value: "FO", label: "FAROE ISLAS" },
    { value: "FJ", label: "FIJI" },
    { value: "PH", label: "FILIPINAS" },
    { value: "FI", label: "FINLANDIA" },
    { value: "GF", label: "FRANCESA GUINEA" },
    { value: "PF", label: "FRANCESA POLINESIA" },
    { value: "TF", label: "FRANCESES,DEL SURESTE TERRITOR" },
    { value: "FR", label: "FRANCIA" },
    { value: "FRM", label: "FRANCIA,METROPOLITANA" },
    { value: "GA", label: "GABON" },
    { value: "GM", label: "GAMBIA" },
    { value: "GE", label: "GEORGIA" },
    { value: "GS", label: "GEORGIA DEL SUR E ISLAS SAND" },
    { value: "GH", label: "GHANA" },
    { value: "GI", label: "GIBRALTAR" },
    { value: "GR", label: "GRECIA" },
    { value: "GD", label: "GRENADA" },
    { value: "GL", label: "GROENLANDIA" },
    { value: "GP", label: "GUADALUPE" },
    { value: "GU", label: "GUAN" },
    { value: "GT", label: "GUATEMALA" },
    { value: "GN", label: "GUINEA" },
    { value: "GW", label: "GUINEA-BISSAU" },
    { value: "GY", label: "GUYANA (ANTIGUA GUYANA INGLESA" },
    { value: "HT", label: "HAITI" },
    { value: "HM", label: "HEARD Y MC DONALD ISLAS" },
    { value: "NL", label: "HOLANDA (PAISES BAJOS DE HOL)" },
    { value: "AN", label: "HOLANDESAS ANTILLAS" },
    { value: "HN", label: "HONDURAS" },
    { value: "HK", label: "HONG KONG" },
    { value: "HU", label: "HUNGRIA" },
    { value: "IN", label: "INDIA" },
    { value: "ID", label: "INDONESIA" },
    { value: "IR", label: "IRAN (REP.ISLAMICA DE )" },
    { value: "IQ", label: "IRAQ" },
    { value: "IE", label: "IRLANDA" },
    { value: "IS", label: "ISLANDIA" },
    { value: "UM", label: "ISLAS MENORES Y ALEJADAS (EEUU" },
    { value: "IL", label: "ISRAEL" },
    { value: "IT", label: "ITALIA" },
    { value: "JM", label: "JAMAICA" },
    { value: "JP", label: "JAPON" },
    { value: "JO", label: "JORDANIA" },
    { value: "KZ", label: "KAZAKSTAN" },
    { value: "KE", label: "KENIA" },
    { value: "KG", label: "KIRGHIZISTAN" },
    { value: "KI", label: "KIRIBATI" },
    { value: "KR", label: "KOREA,REP.DE (KOREA DEL SUR)" },
    { value: "KP", label: "KOREA,REP.POPULAR DEMOCRATICA" },
    { value: "KW", label: "KUWAIT" },
    { value: "LA", label: "LAOS,REPUBLICA POPULAR DEM" },
    { value: "LV", label: "LATVIA" },
    { value: "LS", label: "LESOTHO" },
    { value: "LB", label: "LIBANO" },
    { value: "LR", label: "LIBERIA" },
    { value: "LY", label: "LIBIA ARABE JAMAHIRIYA" },
    { value: "LI", label: "LIECHTENSTEIN" },
    { value: "LT", label: "LITUANIA" },
    { value: "LU", label: "LUXEMBURGO" },
    { value: "MO", label: "MACAU" },
    { value: "MK", label: "MACEDONIA, LA ANT.REP.DE YUGOS" },
    { value: "MG", label: "MADAGASCAR" },
    { value: "MY", label: "MALASIA" },
    { value: "MW", label: "MALAWI" },
    { value: "MV", label: "MALDIVAS" },
    { value: "ML", label: "MALI" },
    { value: "MT", label: "MALTA" },
    { value: "MP", label: "MARIANAS SEPTENTRIONALES ISLAS" },
    { value: "MA", label: "MARRUECOS" },
    { value: "MH", label: "MARSHALL ISLAS" },
    { value: "MQ", label: "MARTINICA" },
    { value: "MU", label: "MAURICIOS" },
    { value: "MR", label: "MAURITANIA" },
    { value: "YT", label: "MAYOTTE" },
    { value: "MX", label: "MEXICO" },
    { value: "FM", label: "MICRONESIA,ESTADO FEDERAL DE" },
    { value: "MD", label: "MOLDAVIA, REPUBLICA DE" },
    { value: "MC", label: "MONACO" },
    { value: "MN", label: "MONGOLIA" },
    { value: "MS", label: "MONTSERRAT" },
    { value: "MZ", label: "MOZAMBIQUE" },
    { value: "MM", label: "MYANMA (ANTIGUA REP.DE BIRMAN)" },
    { value: "NA", label: "NAMIBIA" },
    { value: "NR", label: "NAURO" },
    { value: "CX", label: "NAVIDAD ISLAS" },
    { value: "NP", label: "NEPAL" },
    { value: "NI", label: "NICARAGUA" },
    { value: "NN", label: "NICARAGUA EXPORTACION" },
    { value: "NE", label: "NIGER" },
    { value: "NG", label: "NIGERIA" },
    { value: "NU", label: "NIUE" },
    { value: "NF", label: "NORFOLK ISLAS" },
    { value: "NO", label: "NORUEGA" },
    { value: "NC", label: "NUEVA CALEDONIA" },
    { value: "NZ", label: "NUEVA ZELANDA" },
    { value: "OM", label: "OMAN" },
    { value: "PK", label: "PAKISTAN" },
    { value: "PW", label: "PALAU" },
    { value: "PA", label: "PANAMA" },
    { value: "PG", label: "PAPUA NUEVA GUINEA" },
    { value: "PY", label: "PARAGUAY" },
    { value: "PE", label: "PERU" },
    { value: "PN", label: "PITCAIRN" },
    { value: "PL", label: "POLONIA" },
    { value: "PT", label: "PORTUGAL" },
    { value: "PR", label: "PUERTO RICO" },
    { value: "QA", label: "QATAR" },
    { value: "GB", label: "REINO UNIDO (INGLATERRA GRAN B" },
    { value: "RE", label: "REUNION" },
    { value: "RW", label: "RUANDA" },
    { value: "RO", label: "RUMANIA" },
    { value: "RU", label: "RUSA FEDERACION" },
    { value: "EH", label: "SAHARA DEL OESTE" },
    { value: "KN", label: "SAINT KITTS AND NEVIS" },
    { value: "WS", label: "SAMOA" },
    { value: "AS", label: "SAMOA AMERICANA" },
    { value: "SM", label: "SAN MARINO" },
    { value: "PM", label: "SAN PEDRO Y MIGUELON" },
    { value: "VC", label: "SAN VICENTE Y LAS GRANADINAS" },
    { value: "SH", label: "SANTA HELENA" },
    { value: "LC", label: "SANTA LUCIA" },
    { value: "VA", label: "SANTA SEDE (CIUDAD DEL VATICA)" },
    { value: "ST", label: "SAO TOME Y PRINCIPE" },
    { value: "SA", label: "SAUDITA ARABIA" },
    { value: "SN", label: "SENEGAL" },
    { value: "CS", label: "SERBIA Y MONTENEGRO" },
    { value: "SC", label: "SEYCHELLES ISLAS" },
    { value: "SL", label: "SIERRA LEONA" },
    { value: "OO", label: "SIN ORIGEN" },
    { value: "SG", label: "SINGAPUR" },
    { value: "SY", label: "SIRIA REPUBLICA ARABE" },
    { value: "SB", label: "SOLOMON ISLAS" },
    { value: "SO", label: "SOMALIA" },
    { value: "LK", label: "SRI LANKA (CEILAN)" },
    { value: "SZ", label: "SUAZILANDIA" },
    { value: "SD", label: "SUDAN" },
    { value: "SE", label: "SUECIA" },
    { value: "CH", label: "SUIZA" },
    { value: "ZA", label: "SURAFRICA" },
    { value: "SR", label: "SURINAM (GUAYANA HOLANDESAS)" },
    { value: "SJ", label: "SVALBARD AND JAN MAYEN ISLAS" },
    { value: "TJ", label: "TADJIKISTAN" },
    { value: "TH", label: "TAILANDIA" },
    { value: "TW", label: "TAIWAN, PROVINCIA CHINA DE" },
    { value: "TZ", label: "TANZANIA, REPUBLICA UNIDA DE" },
    { value: "IO", label: "TERRITORIO BRITANICO DEL OCEA" },
    { value: "PS", label: "TERRITORIO PALESTINO OCUPADO" },
    { value: "TL", label: "TIMOR DEL ESTE" },
    { value: "TG", label: "TOGO" },
    { value: "TK", label: "TOKELAU" },
    { value: "TO", label: "TONGA" },
    { value: "TT", label: "TRINIDAD Y TOBAGO" },
    { value: "TN", label: "TUNISIA" },
    { value: "TC", label: "TURCOS Y CAICOS ISLAS" },
    { value: "TM", label: "TURKMENISTAN" },
    { value: "TR", label: "TURQUIA" },
    { value: "TV", label: "TUVALU" },
    { value: "UA", label: "UCRANIA" },
    { value: "UG", label: "UGANDA" },
    { value: "UY", label: "URUGUAY" },
    { value: "UZ", label: "UZBEKISTAN" },
    { value: "VU", label: "VANUATU" },
    { value: "VE", label: "VENEZUELA" },
    { value: "VN", label: "VIETNAM" },
    { value: "VG", label: "VIRGENES ISLAS (BRITANICAS)" },
    { value: "VI", label: "VIRGENES ISLAS (U.S.)" },
    { value: "WF", label: "WALLIS Y FUTUNA ISLAS" },
    { value: "YE", label: "YEMEN" },
    { value: "ZM", label: "ZAMBIA" },
    { value: "ZW", label: "ZIMBABWE" }
];

// Create a map for efficient lookups
export const paisesValueMap = new Map(paises.map(p => [p.label, p.value]));

export const aduanas = [  
    { value: "0610", label: "0610 ADUANA MANAGUA" },
    { value: "6109", label: "6109 DELEGACION MANAGUA" },
    { value: "0110", label: "0110 ADUANA CENTRAL DE CARGA AEREA" },
    { value: "0630", label: "0630 ADUANA TERMINAL AEREA" },
    { value: "0340", label: "0340 PUERTO CORINTO" },
    { value: "0230", label: "0230 GUASAULE" },
    { value: "0220", label: "0220 EL ESPINO" },
    { value: "0240", label: "0240 LAS MANOS"},
    { value: "9010", label: "9010 ADMINISTRACION ZONA FRANCA ASTRO" },
    { value: "0315", label: "0315 EL BLUFF" },
    { value: "9008", label: "9008 ZONA FRANCA EL BLUFF" },
    { value: "6140", label: "6140 EL RAMA PUERTO ESPERANZA" },
    { value: "0640", label: "0640 PUERTO ESPERANZA (EL RAMA)" },
    { value: "6115", label: "6115 ULTRAMAR" },
    { value: "9009", label: "9009 MASAYA" },
    { value: "0250", label: "0250 PEÑAS BLANCAS" },
    { value: "0350", label: "0350 PUERTO SANDINO" },
    { value: "0270", label: "0270 SAN PANCHO LAS TABLILLAS" },
    { value: "9004", label: "9004 ZONA FRANCA JOSE IGNACIO GONZALEZ M" },
    { value: "9011", label: "9011 GERMAN POMARES ORDOÑEZ" },
    { value: "0620", label: "0620 ADUANA POSTAL" },
    { value: "9003", label: "9003 ZONA FRANCA ESTELI" },
    { value: "9006", label: "9006 ZONA FRANCA ARNECON" },
    { value: "9002", label: "9002 ZONA FRANCA SARATOGA" },
    { value: "6135", label: "6135 ZONA FRANCA SENIKA" },
    { value: "9007", label: "9007 ZONA FRANCA INDEX" },
    { value: "9001", label: "9001 ZONA FRANCA INDUSTRIAL LAS MERCEDES" },
];

export const aduanaToShortCode: { [key: string]: string } = {
    "0610": "ACM", // ADUANA CENTRAL MANAGUA
    "6109": "DM",  // DELEGACION MANAGUA
    "0110": "ACCA",// ADUANA CENTRAL DE CARGA AEREA
    "0630": "ATA", // ADUANA TERMINAL AEREA
    "0340": "PC",  // PUERTO CORINTO
    "0230": "GUA", // GUASAULE
    "0220": "EE",  // EL ESPINO
    "0240": "LM",  // LAS MANOS
    "9010": "AZFA",// ADMINISTRACION ZONA FRANCA ASTRO
    "0315": "EB",  // EL BLUFF
    "9008": "ZFEB",// ZONA FRANCA EL BLUFF
    "6140": "ERPE",// EL RAMA PUERTO ESPERANZA
    "0640": "PE",  // PUERTO ESPERANZA (EL RAMA)
    "6115": "ULT", // ULTRAMAR
    "9009": "MAS", // MASAYA
    "0250": "PB",  // PEÑAS BLANCAS
    "0350": "PS",  // PUERTO SANDINO
    "0270": "SPLT",// SAN PANCHO LAS TABLILLAS
    "9004": "ZFJ", // ZONA FRANCA JOSE IGNACIO GONZALEZ M
    "9011": "GPO", // GERMAN POMARES ORDOÑEZ
    "0620": "AP",  // ADUANA POSTAL
    "9003": "ZFE", // ZONA FRANCA ESTELI
    "9006": "ZFA", // ZONA FRANCA ARNECON
    "9002": "ZFS", // ZONA FRANCA SARATOGA
    "6135": "ZFSK",// ZONA FRANCA SENIKA
    "9007": "ZFI", // ZONA FRANCA INDEX
    "9001": "ZFILM",// ZONA FRANCA INDUSTRIAL LAS MERCEDES
};

export const permitOptions = [
    "BOMBEROS",
    "CNRCST",
    "Dictamen Tecnico INE",
    "IPSA",
    "MAGFOR",
    "MARENA",
    "MEFCA",
    "MEM",
    "MINSA",
    "OTROS",
    "TELCOR",
    "VUCEN",
];

export const tiposDeclaracion = [
    { value: "ABR4", label: "DECLARACIÓN ABREVIADA" },
    { value: "ANT4", label: "DECLARACIÓN ANTICIPADA AL ARRIBO DE MERCANCÍAS" },
    { value: "ANT5", label: "DECLARACIÓN ANTICIPADA DE IMPORTACIÓN TEMPORAL" },
    { value: "ANT6", label: "DECLARACIÓN ANTICIPADA DE MERCANCÍAS REIMPORTADAS" },
    { value: "ANC4", label: "DECLARACIÓN ANTICIPADA DE IMP DEF CORINTO" },
    { value: "ANC5", label: "DECLARACIÓN ANTICIPADA DE IMP TEMPORAL CORINTO" },
    { value: "ANC6", label: "DECLARACIÓN ANTICIPADA DE IMP REIMPORTADA CORINTO" },
    { value: "ATA5", label: "ATPA DE BIENES PROVENIENTE DE ZF" },
    { value: "AVO4", label: "DECLARACIÓN DE ABANDONO VOLUNTARIO DE MERCANCÍAS" },
    { value: "DAD7", label: "DEPÓSITO ADUANERO" },
    { value: "DAT7", label: "TRASLADO ENTRE DEPÓSITOS ADUANEROS" },
    { value: "DAV7", label: "INGRESO DE VEHÍCULO TURISMO PARA POSTERIOR REGRESO" },
    { value: "DES4", label: "DESTRUCCIÓN DE MERCANCÍAS EN EL PAÍS (CASO FORTUITO/FUERZA MAYOR)" },
    { value: "DES6", label: "DESTRUCCIÓN DE MERCANCÍAS QUE REINGRESAN" },
    { value: "DME1", label: "DESTRUCCIÓN DE MERCANCÍAS FUERA DEL PAÍS (CASO FORTUITO/FUERZA MAYOR)" },
    { value: "EAO1", label: "EXPORTACIÓN ADUANERA DE OFICIO" },
    { value: "ECD4", label: "DESPACHO DE CORRESPONDENCIA DE LA MODALIDAD DE E" },
    { value: "ECT4", label: "ENTREGA COURIER SUJETA A TRIBUTOS" },
    { value: "ECU4", label: "ENTREGA RÁPIDA O COURIER" },
    { value: "EDD4", label: "DESPACHO DE CORRESPONDENCIA COURIER" },
    { value: "EHD1", label: "EXPORTACIÓN DEFINITIVA DE HIDROCARBUROS Y DERIVADOS" },
    { value: "EHD2", label: "EXPORTACIÓN TEMPORAL DE HIDROCARBUROS Y DERIVADOS" },
    { value: "EMD5", label: "ATPA POR INDUSTRIA DE EXPLORACIÓN MINERA" },
    { value: "EMP5", label: "ATPA POR INDUSTRIA DE EXPLORACIÓN MINERA (ZONA FRANCA)" },
    { value: "EMZ5", label: "ATPA POR INDUSTRIA DE EXPLORACIÓN MINERA (ZF)" },
    { value: "ENU4", label: "ENVÍOS QUE POR SU NATURALEZA REQUIEREN DESPACHO URGENTE" },
    { value: "EPC4", label: "ENVÍOS POSTALES COMERCIALES" },
    { value: "EPD4", label: "ENVÍOS POSTALES NO COMERCIALES" },
    { value: "EPF1", label: "EXPORTACIÓN DEFINITIVA DE MERCANCÍAS PERECEDERAS Y FRESCAS" },
    { value: "EPF2", label: "EXPORTACIÓN TEMPORAL DE MERCANCÍAS PERECEDERAS Y FRESCAS" },
    { value: "EPN4", label: "ENVÍOS POSTALES NO COMERCIALES" },
    { value: "EQD4", label: "MERCANCÍAS DISTINTAS DEL EQUIPAJE NO ACOMPAÑADO (VIAJERO)" },
    { value: "EQF4", label: "IMPORTACIÓN DEFINITIVA SUJETA AL PAGO DEL FACTOR DEL 2%" },
    { value: "EQS4", label: "IMPORTACIÓN DEFINITIVA SUJETA AL FACTOR DEL 25%" },
    { value: "EQT4", label: "MERCANCÍAS DISTINTAS DEL EQUIPAJE NO ACOMPAÑADO" },
    { value: "EQU4", label: "IMPORTACIÓN SUJETA AL FACTOR DEL 25%, EQUIPAJE NO ACOMPAÑADO" },
    { value: "EQV4", label: "MERCANCÍAS DISTINTAS DEL EQUIPAJE QUE TRAE EL VIAJERO" },
    { value: "ESD4", label: "ENVÍOS DE SOCORRO (DESDE DEPÓSITO ADUANERO)" },
    { value: "ETV2", label: "SALIDA TEMPORAL DE VEHÍCULOS DE TURISMO" },
    { value: "EUD4", label: "ENVÍOS URGENTES DESDE DEPÓSITO ADUANERO" },
    { value: "EVS4", label: "ENVÍOS DE SOCORRO" },
    { value: "EXP1", label: "EXPORTACIÓN DEFINITIVA" },
    { value: "EXP2", label: "EXPORTACIÓN TEMPORAL CON REIMPORTACIÓN" },
    { value: "EXP8", label: "TRÁNSITO ADUANERO INTERNACIONAL TERRESTRE DE EXPORTACIÓN" },
    { value: "EXV3", label: "REEXPORTACIÓN DEFINITIVA DE VEHÍCULOS DE TURISMO" },
    { value: "EZP2", label: "EXPORTACIÓN TEMPORAL POR ALQUILER O PRÉSTAMO" },
    { value: "EZS2", label: "EXPORTACIÓN TEMPORAL POR ALQUILER O PRÉSTAMO (OTRA MODALIDAD)" },
    { value: "FAE1", label: "EXPORTACIÓN DEFINITIVA CON FAUCA" },
    { value: "FAT4", label: "IMPORTACIÓN CON FAUCA TEMPORAL" },
    { value: "FAT5", label: "ADMISIÓN DE MERCANCÍAS AMPARADAS EN FAUCA" },
    { value: "GCN1", label: "EXPORTACIÓN DEFINITIVA GRAN CANAL" },
    { value: "GCN2", label: "EXPORTACIÓN TEMPORAL GRAN CANAL" },
    { value: "GCN3", label: "REEXPORTACIÓN GRAN CANAL" },
    { value: "GCN4", label: "IMPORTACIÓN DEFINITIVA GRAN CANAL" },
    { value: "GCN5", label: "IMPORTACIÓN TEMPORAL GRAN CANAL" },
    { value: "GCN6", label: "REIMPORTACIÓN GRAN CANAL" },
    { value: "GCN7", label: "DEPÓSITO ADUANERO GRAN CANAL" },
    { value: "IAO4", label: "IMPORTACIÓN ADUANERA DE OFICIO" },
    { value: "ICN5", label: "IMPORTACIÓN TEMPORAL VEHÍCULOS TURISMO" },
    { value: "ICR5", label: "ATPA DE PRODUCTOS COMPENSADORES DEVUELTOS" },
    { value: "ICT4", label: "IMPORTACIÓN DEFINITIVA DE COURIER SUJETA A TRIBUTOS" },
    { value: "IEM5", label: "ADMISIÓN TEMPORAL PARA PERFECCIONAMIENTO ACTIVO" },
    { value: "IGE5", label: "IMPORTACIÓN TEMPORAL CON GUÍA AUTORIZADA" },
    { value: "IHD4", label: "IMPORTACIÓN DEFINITIVA DE HIDROCARBUROS Y DERIVADOS" },
    { value: "IHD5", label: "IMPORTACIÓN TEMPORAL DE HIDROCARBUROS Y DERIVADOS" },
    { value: "IMD4", label: "IMPORTACIÓN DEFINITIVA DESDE DEPÓSITO ADUANERO" },
    { value: "IME4", label: "IMPORTACIÓN DEFINITIVA DE MERCANCÍAS NO DECLARADAS/MANIFESTADAS" },
    { value: "IMM5", label: "IMPORTACIÓN TEMPORAL DE VEHÍCULOS DE TURISMO" },
    { value: "IMO4", label: "IMPORTACIÓN DEFINITIVA DE OFICIO" },
    { value: "IMP4", label: "IMPORTACIÓN DEFINITIVA" },
    { value: "IMP5", label: "IMPORTACIÓN TEMPORAL CON REEXPORTACIÓN" },
    { value: "IMP8", label: "TRÁNSITO ADUANERO INTERNACIONAL" },
    { value: "IMS4", label: "IMPORTACIÓN DEFINITIVA DE PRODUCTOS DEFECTUOSOS" },
    { value: "IMT4", label: "IMPORTACIÓN DEFINITIVA DE MERCANCÍAS COURIER" },
    { value: "IMT5", label: "TRASLADO ENTRE BENEFICIARIOS DE ATPA" },
    { value: "IMZ5", label: "IMPORTACIÓN TEMPORAL DESDE ZONA FRANCA" },
    { value: "IPF4", label: "IMPORTACIÓN DEFINITIVA DE PERECEDEROS Y FRESCOS" },
    { value: "IPF5", label: "IMPORTACIÓN TEMPORAL DE PERECEDEROS Y FRESCOS" },
    { value: "ISG5", label: "IMPORTACIÓN TEMPORAL AUTORIZADA POR FACULTAD ADUANERA" },
    { value: "ITS5", label: "IMPORTACIÓN TEMPORAL DE ENVÍOS DE SOCORRO" },
    { value: "ITZ5", label: "ATPA INDUSTRIA DE MINERÍA EN ZONA FRANCA" },
    { value: "IVM5", label: "REINGRESO IMPORTACIÓN TEMPORAL (MODALIDAD 1)" },
    { value: "IVP5", label: "IMPORTACIÓN TEMPORAL DE VEHÍCULOS DE TURISMO" },
    { value: "IVT5", label: "REINGRESO IMPORTACIÓN TEMPORAL (MODALIDAD 2)" },
    { value: "IZD4", label: "IMPORTACIÓN DEFINITIVA DESDE ZONA FRANCA" },
    { value: "IZP4", label: "IMPORTACIÓN DEFINITIVA DESDE ZONA FRANCA" },
    { value: "PEF4", label: "IMPORTACIÓN DEFINITIVA CON EXENCIÓN DE IMPUESTOS" },
    { value: "PFD4", label: "IMPORTACIÓN DEFINITIVA DE PEQUEÑOS ENVÍOS FAMILIARES" },
    { value: "PRV7", label: "DECLARACIÓN PROVISIONAL DE MERCANCÍAS A GRANEL Y OTRAS" },
    { value: "PRV9", label: "DECLARACIÓN PROVISIONAL DE MERCANCÍAS A GRANEL Y OTRAS" },
    { value: "REH3", label: "REEXPORTACIÓN DE HIDROCARBUROS Y DERIVADOS" },
    { value: "RID6", label: "REIMPORTACIÓN DESDE DEPÓSITO ADUANERO" },
    { value: "RIF6", label: "REIMPORTACIÓN DE PERECEDEROS Y FRESCOS" },
    { value: "RIH6", label: "REIMPORTACIÓN DE HIDROCARBUROS Y DERIVADOS" },
    { value: "RIM6", label: "REIMPORTACIÓN" },
    { value: "RIP6", label: "REIMPORTACIÓN SUJETA A TRIBUTOS" },
    { value: "RIZ6", label: "REIMPORTACIÓN DESDE ZONA FRANCA" },
    { value: "RPF3", label: "REEXPORTACIÓN DE PERECEDEROS Y FRESCOS" },
    { value: "RVX3", label: "REEXPORTACIÓN DE VEHÍCULOS TURISMO" },
    { value: "RXP3", label: "REEXPORTACIÓN" },
    { value: "SUB4", label: "ABANDONO Y SUBASTAS" },
    { value: "TED4", label: "IMPORTACIÓN CON EXONERACIÓN APLICABLE DESPUÉS DE…" },
    { value: "TEM4", label: "IMPORTACIÓN CON EXONERACIÓN APLICABLE DESPUÉS DE…" },
    { value: "TEZ4", label: "IMPORTACIÓN CON EXONERACIÓN APLICABLE DESPUÉS DE…" },
    { value: "TLI9", label: "INGRESO DE MERCANCÍAS A TIENDAS LIBRES" },
    { value: "TLN9", label: "INGRESO DE MERCANCÍAS NACIONALES A TIENDAS LIBRES" },
    { value: "TLT9", label: "TRASLADO ENTRE TIENDAS LIBRES" },
    { value: "TSG5", label: "IMPORTACIÓN TEMPORAL CON REEXPORTACIÓN EN EL MISMO ESTADO" },
    { value: "ZFI9", label: "INGRESO A ZONA FRANCA" },
    { value: "ZFN9", label: "INGRESO A ZONA FRANCA DE PRODUCTOS NACIONALES" },
    { value: "ZFP9", label: "INGRESO A ZONA FRANCA DE PERECEDEROS Y FRESCOS" },
    { value: "ZFT9", label: "TRASLADO DE MERCANCÍAS ENTRE EMPRESAS DE ZONAS FRANCAS" },
];

export const estadosMercancia = [
    { value: "1", label: "Nuevas" },
    { value: "2", label: "Usadas" },
    { value: "3", label: "Averiadas" },
    { value: "4", label: "Reconstruida" },
    { value: "5", label: "Incompletas" },
    { value: "6", label: "Desarmadas" },
    { value: "7", label: "Desmontadas" },
    { value: "8", label: "Otros" },
];

    
export const unidadEstadistica = [
	{ value: "1/16 GL", label: "1/16 GL 1/16 GALON" },		
	{ value: "1/2 GL", label: "1/2 GL 1/2 GALON" },		
	{ value: "1/4 GL", label: "1/4 GL 1/4 DE GALON" },		
	{ value: "1/8 GL", label: "1/8 GL 1/8 GALON" },		
	{ value: "1A", label: "1A TAMBOR DE ACERO" },		
	{ value: "4C", label: "4C CAJA DE MADERA NATURAL" },		
	{ value: "4D", label: "4D CAJA DE MADERA CONTRACHAPADA" },		
	{ value: "4G", label: "4G CAJA DE CARTON" },		
	{ value: "5 BULTOS", label: "5 BULTOS" },		
	{ value: "5H", label: "5H BOLSA DE TEJIDO DE PLASTICO" },		
	{ value: "5M", label: "5M BOLSA DE PAPEL" },		
	{ value: "7G", label: "7G BLISTER" },		
	{ value: "AG", label: "AG PALETAS EMBALADAS" },		
	{ value: "AP", label: "AP AMPOLLA PROTEGIDA" },		
	{ value: "BAN", label: "BAN BANDEJA" },		
	{ value: "BB", label: "BB BOBINAS" },		
	{ value: "BD", label: "BD BIDON" },		
	{ value: "BDE", label: "BDE BALDE" },		
	{ value: "BE", label: "BE BULTO" },		
	{ value: "BG", label: "BG BOLSA" },		
	{ value: "BH", label: "BH ATADO" },		
	{ value: "BOS", label: "BOS BOTES" },		
	{ value: "BQ", label: "BQ BOTELLA CILINDRICA PROTEGIDA" },		
	{ value: "BR", label: "BR BARRIL" },		
	{ value: "BTL", label: "BTL BOTELLA" },		
	{ value: "CA", label: "CA CAJON" },		
	{ value: "CAN", label: "CAN CANASTILLA" },		
	{ value: "CAR", label: "CAR CARTONES" },		
	{ value: "CCH", label: "CCH CARTUCHO" },		
	{ value: "CEN", label: "CEN CENTENARES" },		
	{ value: "CJA", label: "CJA CAJA" },		
	{ value: "CJT", label: "CJT CONJUNTO" },		
	{ value: "CM", label: "CM CENTIMETROS" },		
	{ value: "CMC", label: "CMC CENTIMETROS CUBICOS" },		
	{ value: "CRA", label: "CRA CARRETE" },		
	{ value: "CRG", label: "CRG CARGA" },		
	{ value: "CT", label: "CT CARTON" },		
	{ value: "CUB", label: "CUB CUBETA" },		
	{ value: "CY", label: "CY CILINDRO" },		
	{ value: "DK", label: "DK CAJA DE CARTON A GRANEL" },		
	{ value: "DN", label: "DN DISPENSADOR" },		
	{ value: "DO", label: "DO DOCENA" },		
	{ value: "DPL", label: "DPL DISPLAY" },		
	{ value: "EA", label: "EA EA" },		
	{ value: "EC", label: "EC BOLSA PLASTICA" },		
	{ value: "EN", label: "EN SOBRE" },		
	{ value: "EQ", label: "EQ EQUIPO" },		
	{ value: "EST", label: "EST ESTUCHE" },		
	{ value: "FD", label: "FD CAJA ENMARCADA" },		
	{ value: "FSK", label: "FSK FRASCO" },		
	{ value: "GAL", label: "GAL GALONES" },		
	{ value: "GR", label: "GR GRUESAS" },		
	{ value: "GRS", label: "GRS GRAMOS" },		
	{ value: "HG", label: "HG PIPA" },		
	{ value: "HOJ", label: "HOJ HOJA" },		
	{ value: "IH", label: "IH TAMBOR DE PLASTICO" },		
	{ value: "JGO", label: "JGO JUEGOS" },		
	{ value: "KGS", label: "KGS KILOGRAMOS" },		
	{ value: "KMS", label: "KILOMETROS" },		
	{ value: "KIT", label: "KIT KIT" },		
	{ value: "LB", label: "LB LIBRAS" },		
	{ value: "LNF", label: "LNF PIE LINEAL" },		
	{ value: "LO", label: "LO LOTE" },		
	{ value: "LTA", label: "LTA LATA" },		
	{ value: "LTS", label: "LTS LITROS" },		
	{ value: "M", label: "M2 METROS CUADRADOS" },		
	{ value: "M", label: "M3 METROS CUBICOS" },		
	{ value: "MK", label: "MK MK" },		
	{ value: "ML", label: "ML MILILITRO" },		
	{ value: "MMM", label: "MMM MILIMETROS" },		
	{ value: "MTL", label: "MTL METRO LINEAL" },		
	{ value: "MTS", label: "MTS METROS" },		
	{ value: "P", label: "P3 PIE CUBICO" },		
	{ value: "PAQ", label: "PAQ PAQUETES" },		
	{ value: "PAR", label: "PAR PAR" },		
	{ value: "PC", label: "PC PACA" },		
	{ value: "PIE", label: "PIE PIES" },		
	{ value: "PL", label: "PL PLIEGOS" },		
	{ value: "PLG", label: "PLG PLIEGO" },		
	{ value: "PRS", label: "PRS PARES" },		
	{ value: "PUL", label: "PUL PULGADA" },		
	{ value: "PX", label: "PX PALETA" },		
	{ value: "PZA", label: "PZA PIEZAS" },		
	{ value: "QQ", label: "QQ QUINTAL" },		
	{ value: "RO", label: "RO ROLLO" },		
	{ value: "RS", label: "RS RESMA" },		
	{ value: "SA", label: "SA SACO" },		
	{ value: "SQF", label: "SQF PIES CUADRADOS" },		
	{ value: "ST", label: "ST SET" },		
	{ value: "TA", label: "TA TAMBO" },		
	{ value: "TAB", label: "TAB TABLETA" },		
	{ value: "TAM", label: "TAM TAMBOR" },		
	{ value: "TARRO", label: "TARRO TARRO" },		
	{ value: "TB", label: "TB TAMBOR" },		
	{ value: "TH", label: "TH MILLAR" },		
	{ value: "TM", label: "TM TONELADA METRICA" },		
	{ value: "TML", label: "TML TONELADA METRICAS LIQUIDAS" },		
	{ value: "TN", label: "TN TONELADA" },		
	{ value: "TO", label: "TO TOTES" },		
	{ value: "TS", label: "TS FARDOS" },		
	{ value: "TUB", label: "TUB TUBO" },		
	{ value: "UND", label: "UND UNIDAD" },		
	{ value: "UNDS", label: "UNDS UNIDADES" },		
	{ value: "VIL", label: "VIL VIALES" },		
	{ value: "YRD", label: "YRD YARDA" },		
];
